---
- name: Debug topic messages
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: bobbycar-cluster-kafka-bootstrap
        port: 9092
        topic: bobbycar-speed-alert
        group_id:

  rules:
    - name: triage issue
      condition: event is defined
      action:
        debug:
