---
- name: speedAvg events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: bobbycar-cluster-kafka-bootstrap
        port: 9092
        topic: bobbycar-speed-alert
        group_id:

  rules:
    - name: High speed average
      condition: 
        all:
          - event.speedAvg is defined
          - event.speedAvg > 100
      action:
        debug:
